apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - image-api.local
    secretName: image-api-tls
  rules:
  - host: image-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: image-api-service
            port:
              number: 80
